// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231107233035_llenar-base")]
    partial class llenarbase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto.Ciudad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("ciudad", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Buenos Aires"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Córdoba"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Rosario"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Mendoza"
                        },
                        new
                        {
                            id = 5,
                            nombre = "La Plata"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Mar del Plata"
                        },
                        new
                        {
                            id = 7,
                            nombre = "San Miguel de Tucumán"
                        },
                        new
                        {
                            id = 8,
                            nombre = "Salta"
                        },
                        new
                        {
                            id = 9,
                            nombre = "Santa Fe"
                        },
                        new
                        {
                            id = 10,
                            nombre = "San Juan"
                        },
                        new
                        {
                            id = 11,
                            nombre = "Resistencia"
                        },
                        new
                        {
                            id = 12,
                            nombre = "Corrientes"
                        },
                        new
                        {
                            id = 13,
                            nombre = "Posadas"
                        },
                        new
                        {
                            id = 14,
                            nombre = "Neuquén"
                        },
                        new
                        {
                            id = 15,
                            nombre = "Formosa"
                        },
                        new
                        {
                            id = 16,
                            nombre = "Bahía Blanca"
                        },
                        new
                        {
                            id = 17,
                            nombre = "San Salvador de Jujuy"
                        },
                        new
                        {
                            id = 18,
                            nombre = "Río Cuarto"
                        },
                        new
                        {
                            id = 19,
                            nombre = "Comodoro Rivadavia"
                        },
                        new
                        {
                            id = 20,
                            nombre = "Concordia"
                        });
                });

            modelBuilder.Entity("Proyecto.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<int>("ciudad_fk")
                        .HasColumnType("int");

                    b.Property<double>("costo")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("ciudad_fk");

                    b.ToTable("hotel", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacidad = 101,
                            ciudad_fk = 7,
                            costo = 21000.0,
                            nombre = "Hotel Buenos Aires"
                        },
                        new
                        {
                            id = 2,
                            capacidad = 80,
                            ciudad_fk = 2,
                            costo = 22000.0,
                            nombre = "Hotel Rosario"
                        },
                        new
                        {
                            id = 3,
                            capacidad = 120,
                            ciudad_fk = 3,
                            costo = 27000.0,
                            nombre = "Hotel Córdoba"
                        },
                        new
                        {
                            id = 4,
                            capacidad = 90,
                            ciudad_fk = 4,
                            costo = 24000.0,
                            nombre = "Hotel Mendoza"
                        },
                        new
                        {
                            id = 5,
                            capacidad = 70,
                            ciudad_fk = 5,
                            costo = 21000.0,
                            nombre = "Hotel San Juan"
                        },
                        new
                        {
                            id = 6,
                            capacidad = 110,
                            ciudad_fk = 6,
                            costo = 26000.0,
                            nombre = "Hotel Mar del Plata"
                        },
                        new
                        {
                            id = 7,
                            capacidad = 95,
                            ciudad_fk = 7,
                            costo = 23500.0,
                            nombre = "Hotel Tucumán"
                        },
                        new
                        {
                            id = 8,
                            capacidad = 75,
                            ciudad_fk = 8,
                            costo = 22500.0,
                            nombre = "Hotel Salta"
                        },
                        new
                        {
                            id = 9,
                            capacidad = 85,
                            ciudad_fk = 9,
                            costo = 24500.0,
                            nombre = "Hotel Jujuy"
                        },
                        new
                        {
                            id = 10,
                            capacidad = 105,
                            ciudad_fk = 10,
                            costo = 25500.0,
                            nombre = "Hotel Neuquén"
                        },
                        new
                        {
                            id = 11,
                            capacidad = 80,
                            ciudad_fk = 1,
                            costo = 22000.0,
                            nombre = "Hotel La Plata"
                        },
                        new
                        {
                            id = 12,
                            capacidad = 110,
                            ciudad_fk = 2,
                            costo = 26500.0,
                            nombre = "Hotel Santa Fe"
                        },
                        new
                        {
                            id = 13,
                            capacidad = 90,
                            ciudad_fk = 3,
                            costo = 23000.0,
                            nombre = "Hotel San Luis"
                        },
                        new
                        {
                            id = 14,
                            capacidad = 70,
                            ciudad_fk = 4,
                            costo = 21000.0,
                            nombre = "Hotel Formosa"
                        },
                        new
                        {
                            id = 15,
                            capacidad = 100,
                            ciudad_fk = 5,
                            costo = 25000.0,
                            nombre = "Hotel Entre Ríos"
                        },
                        new
                        {
                            id = 16,
                            capacidad = 120,
                            ciudad_fk = 6,
                            costo = 22000.0,
                            nombre = "Hotel Catamarca"
                        },
                        new
                        {
                            id = 17,
                            capacidad = 120,
                            ciudad_fk = 7,
                            costo = 27500.0,
                            nombre = "Hotel La Rioja"
                        },
                        new
                        {
                            id = 18,
                            capacidad = 95,
                            ciudad_fk = 8,
                            costo = 24000.0,
                            nombre = "Hotel Chaco"
                        },
                        new
                        {
                            id = 19,
                            capacidad = 75,
                            ciudad_fk = 9,
                            costo = 22500.0,
                            nombre = "Hotel Tierra del Fuego"
                        },
                        new
                        {
                            id = 20,
                            capacidad = 105,
                            ciudad_fk = 10,
                            costo = 25500.0,
                            nombre = "Hotel Santa Cruz"
                        },
                        new
                        {
                            id = 2021,
                            capacidad = 101,
                            ciudad_fk = 7,
                            costo = 21000.0,
                            nombre = "PRUEBA"
                        });
                });

            modelBuilder.Entity("Proyecto.ReservaHotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaDesde")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fechaHasta")
                        .HasColumnType("datetime");

                    b.Property<int>("hotel_fk")
                        .HasColumnType("int");

                    b.Property<double>("pagado")
                        .HasColumnType("float");

                    b.Property<int>("usuarioRH_fk")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hotel_fk");

                    b.HasIndex("usuarioRH_fk");

                    b.ToTable("reservaHotel", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 1,
                            pagado = 150000.0,
                            usuarioRH_fk = 1
                        },
                        new
                        {
                            id = 2,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 11, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 2,
                            pagado = 120000.0,
                            usuarioRH_fk = 2
                        },
                        new
                        {
                            id = 3,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 11, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 3,
                            pagado = 170000.0,
                            usuarioRH_fk = 3
                        },
                        new
                        {
                            id = 4,
                            cantPersonas = 2,
                            fechaDesde = new DateTime(2023, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 4,
                            pagado = 140000.0,
                            usuarioRH_fk = 4
                        },
                        new
                        {
                            id = 5,
                            cantPersonas = 2,
                            fechaDesde = new DateTime(2023, 11, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 11, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 5,
                            pagado = 110000.0,
                            usuarioRH_fk = 5
                        },
                        new
                        {
                            id = 6,
                            cantPersonas = 2,
                            fechaDesde = new DateTime(2023, 10, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 1,
                            pagado = 150000.0,
                            usuarioRH_fk = 6
                        },
                        new
                        {
                            id = 7,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 12, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 12, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 2,
                            pagado = 120000.0,
                            usuarioRH_fk = 7
                        },
                        new
                        {
                            id = 8,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 9, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 3,
                            pagado = 170000.0,
                            usuarioRH_fk = 8
                        },
                        new
                        {
                            id = 9,
                            cantPersonas = 2,
                            fechaDesde = new DateTime(2023, 11, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 11, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 4,
                            pagado = 140000.0,
                            usuarioRH_fk = 9
                        },
                        new
                        {
                            id = 10,
                            cantPersonas = 2,
                            fechaDesde = new DateTime(2023, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 12, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 5,
                            pagado = 110000.0,
                            usuarioRH_fk = 10
                        },
                        new
                        {
                            id = 1002,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 1,
                            pagado = 150000.0,
                            usuarioRH_fk = 3
                        },
                        new
                        {
                            id = 2007,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 31, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 2,
                            pagado = 120000.0,
                            usuarioRH_fk = 1024
                        },
                        new
                        {
                            id = 2008,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 5,
                            pagado = 110000.0,
                            usuarioRH_fk = 1024
                        },
                        new
                        {
                            id = 2009,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 6,
                            pagado = 160000.0,
                            usuarioRH_fk = 1024
                        },
                        new
                        {
                            id = 2010,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 7,
                            pagado = 135000.0,
                            usuarioRH_fk = 1024
                        },
                        new
                        {
                            id = 2011,
                            cantPersonas = 1,
                            fechaDesde = new DateTime(2023, 10, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaHasta = new DateTime(2023, 10, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            hotel_fk = 5,
                            pagado = 110000.0,
                            usuarioRH_fk = 1024
                        });
                });

            modelBuilder.Entity("Proyecto.ReservaVuelo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<double>("pagado")
                        .HasColumnType("float");

                    b.Property<int>("usuarioRV_fk")
                        .HasColumnType("int");

                    b.Property<int>("vuelo_fk")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuarioRV_fk");

                    b.HasIndex("vuelo_fk");

                    b.ToTable("reservaVuelo", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            cantPersonas = 1,
                            pagado = 120000.0,
                            usuarioRV_fk = 1,
                            vuelo_fk = 1
                        },
                        new
                        {
                            id = 2,
                            cantPersonas = 1,
                            pagado = 110000.0,
                            usuarioRV_fk = 2,
                            vuelo_fk = 2
                        },
                        new
                        {
                            id = 3,
                            cantPersonas = 1,
                            pagado = 140000.0,
                            usuarioRV_fk = 3,
                            vuelo_fk = 3
                        },
                        new
                        {
                            id = 4,
                            cantPersonas = 1,
                            pagado = 125000.0,
                            usuarioRV_fk = 4,
                            vuelo_fk = 4
                        },
                        new
                        {
                            id = 5,
                            cantPersonas = 2,
                            pagado = 130000.0,
                            usuarioRV_fk = 5,
                            vuelo_fk = 5
                        },
                        new
                        {
                            id = 6,
                            cantPersonas = 2,
                            pagado = 120000.0,
                            usuarioRV_fk = 6,
                            vuelo_fk = 1
                        },
                        new
                        {
                            id = 7,
                            cantPersonas = 2,
                            pagado = 110000.0,
                            usuarioRV_fk = 7,
                            vuelo_fk = 2
                        },
                        new
                        {
                            id = 8,
                            cantPersonas = 1,
                            pagado = 140000.0,
                            usuarioRV_fk = 8,
                            vuelo_fk = 3
                        },
                        new
                        {
                            id = 9,
                            cantPersonas = 2,
                            pagado = 125000.0,
                            usuarioRV_fk = 9,
                            vuelo_fk = 4
                        },
                        new
                        {
                            id = 10,
                            cantPersonas = 2,
                            pagado = 130000.0,
                            usuarioRV_fk = 10,
                            vuelo_fk = 5
                        },
                        new
                        {
                            id = 1002,
                            cantPersonas = 1,
                            pagado = 120000.0,
                            usuarioRV_fk = 3,
                            vuelo_fk = 1
                        },
                        new
                        {
                            id = 2010,
                            cantPersonas = 1,
                            pagado = 125000.0,
                            usuarioRV_fk = 1024,
                            vuelo_fk = 4
                        },
                        new
                        {
                            id = 2011,
                            cantPersonas = 1,
                            pagado = 130000.0,
                            usuarioRV_fk = 1024,
                            vuelo_fk = 5
                        });
                });

            modelBuilder.Entity("Proyecto.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<double>("credito")
                        .HasColumnType("float");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Pérez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1000000.0,
                            dni = 12345678,
                            intentosFallidos = 0,
                            isAdmin = true,
                            mail = "juan@gmail.com",
                            nombre = "Juan"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Gómez",
                            bloqueado = false,
                            clave = "123",
                            credito = 800000.0,
                            dni = 98765432,
                            intentosFallidos = 0,
                            isAdmin = true,
                            mail = "maria@gmail.com",
                            nombre = "María"
                        },
                        new
                        {
                            id = 3,
                            apellido = "López",
                            bloqueado = false,
                            clave = "123",
                            credito = 500000.0,
                            dni = 45678901,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "carlos@gmail.com",
                            nombre = "Carlos"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Martínez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 78436532,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "ana@gmail.com",
                            nombre = "Ana"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Rodríguez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 12344356,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "laura@gmail.com",
                            nombre = "Laura"
                        },
                        new
                        {
                            id = 6,
                            apellido = "Sánchez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 41234324,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "eduardo@gmail.com",
                            nombre = "Eduardo"
                        },
                        new
                        {
                            id = 7,
                            apellido = "Fernández",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 76474567,
                            intentosFallidos = 0,
                            isAdmin = true,
                            mail = "lucia@gmail.com",
                            nombre = "Lucía"
                        },
                        new
                        {
                            id = 8,
                            apellido = "García",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 98667667,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "javier@gmail.com",
                            nombre = "Javier"
                        },
                        new
                        {
                            id = 9,
                            apellido = "Hernández",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 23455433,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "sofia@gmail.com",
                            nombre = "Sofía"
                        },
                        new
                        {
                            id = 10,
                            apellido = "Pérez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 74545345,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "carlos2@gmail.com",
                            nombre = "Carlos"
                        },
                        new
                        {
                            id = 11,
                            apellido = "López",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 12313455,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "mariana@gmail.com",
                            nombre = "Mariana"
                        },
                        new
                        {
                            id = 12,
                            apellido = "Martínez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 53467454,
                            intentosFallidos = 0,
                            isAdmin = true,
                            mail = "andres@gmail.com",
                            nombre = "Andrés"
                        },
                        new
                        {
                            id = 13,
                            apellido = "Gómez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 23467636,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "valentina@gmail.com",
                            nombre = "Valentina"
                        },
                        new
                        {
                            id = 14,
                            apellido = "Santos",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 43765457,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "diego@gmail.com",
                            nombre = "Diego"
                        },
                        new
                        {
                            id = 15,
                            apellido = "Torres",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 43254756,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "marcela@gmail.com",
                            nombre = "Marcela"
                        },
                        new
                        {
                            id = 16,
                            apellido = "Díaz",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 78787878,
                            intentosFallidos = 0,
                            isAdmin = true,
                            mail = "alejandro@gmail.com",
                            nombre = "Alejandro"
                        },
                        new
                        {
                            id = 17,
                            apellido = "Ramírez",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 12344321,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "luis@gmail.com",
                            nombre = "Luis"
                        },
                        new
                        {
                            id = 18,
                            apellido = "Soto",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 98776655,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "ana2@gmail.com",
                            nombre = "Ana"
                        },
                        new
                        {
                            id = 19,
                            apellido = "Silva",
                            bloqueado = false,
                            clave = "123",
                            credito = 1200000.0,
                            dni = 11223344,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "juan2@gmail.com",
                            nombre = "Juan"
                        },
                        new
                        {
                            id = 1023,
                            apellido = "prueba",
                            bloqueado = false,
                            clave = "123",
                            credito = 1000000.0,
                            dni = 12348765,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "prueba@gmail.com",
                            nombre = "prueba"
                        },
                        new
                        {
                            id = 1024,
                            apellido = "PRUEBA",
                            bloqueado = false,
                            clave = "123",
                            credito = 10000000.0,
                            dni = 123345,
                            intentosFallidos = 0,
                            isAdmin = false,
                            mail = "PRUEBA",
                            nombre = "HOLA"
                        });
                });

            modelBuilder.Entity("Proyecto.UsuarioHotel", b =>
                {
                    b.Property<int>("usuario_fk")
                        .HasColumnType("int");

                    b.Property<int>("hotel_fk")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("usuario_fk", "hotel_fk");

                    b.HasIndex("hotel_fk");

                    b.ToTable("usuarioHotel");

                    b.HasData(
                        new
                        {
                            usuario_fk = 1,
                            hotel_fk = 1,
                            cantidad = 2
                        },
                        new
                        {
                            usuario_fk = 2,
                            hotel_fk = 2,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 3,
                            hotel_fk = 1,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 3,
                            hotel_fk = 3,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 4,
                            hotel_fk = 4,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 5,
                            hotel_fk = 5,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 6,
                            hotel_fk = 1,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 7,
                            hotel_fk = 2,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 8,
                            hotel_fk = 3,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 9,
                            hotel_fk = 4,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 10,
                            hotel_fk = 5,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 18,
                            hotel_fk = 1,
                            cantidad = 2
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 1,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 2,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 5,
                            cantidad = 2
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 6,
                            cantidad = 0
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 7,
                            cantidad = 1
                        },
                        new
                        {
                            usuario_fk = 1024,
                            hotel_fk = 2021,
                            cantidad = 9
                        });
                });

            modelBuilder.Entity("Proyecto.UsuarioVuelo", b =>
                {
                    b.Property<int>("usuario_fk")
                        .HasColumnType("int");

                    b.Property<int>("vuelo_fk")
                        .HasColumnType("int");

                    b.HasKey("usuario_fk", "vuelo_fk");

                    b.HasIndex("vuelo_fk");

                    b.ToTable("usuarioVuelo");

                    b.HasData(
                        new
                        {
                            usuario_fk = 1,
                            vuelo_fk = 1
                        },
                        new
                        {
                            usuario_fk = 2,
                            vuelo_fk = 2
                        },
                        new
                        {
                            usuario_fk = 3,
                            vuelo_fk = 1
                        },
                        new
                        {
                            usuario_fk = 3,
                            vuelo_fk = 3
                        },
                        new
                        {
                            usuario_fk = 4,
                            vuelo_fk = 4
                        },
                        new
                        {
                            usuario_fk = 5,
                            vuelo_fk = 5
                        },
                        new
                        {
                            usuario_fk = 6,
                            vuelo_fk = 1
                        },
                        new
                        {
                            usuario_fk = 7,
                            vuelo_fk = 2
                        },
                        new
                        {
                            usuario_fk = 8,
                            vuelo_fk = 3
                        },
                        new
                        {
                            usuario_fk = 9,
                            vuelo_fk = 4
                        },
                        new
                        {
                            usuario_fk = 10,
                            vuelo_fk = 5
                        },
                        new
                        {
                            usuario_fk = 18,
                            vuelo_fk = 1
                        },
                        new
                        {
                            usuario_fk = 1024,
                            vuelo_fk = 1
                        },
                        new
                        {
                            usuario_fk = 1024,
                            vuelo_fk = 4
                        },
                        new
                        {
                            usuario_fk = 1024,
                            vuelo_fk = 5
                        });
                });

            modelBuilder.Entity("Proyecto.Vuelo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aerolinea")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("avion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<double>("costo")
                        .HasColumnType("float");

                    b.Property<int>("destino_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("origen_fk")
                        .HasColumnType("int");

                    b.Property<int>("vendido")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("destino_fk");

                    b.HasIndex("origen_fk");

                    b.ToTable("vuelo", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Boeing 747",
                            capacidad = 150,
                            costo = 22000.0,
                            destino_fk = 3,
                            fecha = new DateTime(2023, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 1,
                            vendido = 0
                        },
                        new
                        {
                            id = 2,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Airbus A320",
                            capacidad = 120,
                            costo = 21000.0,
                            destino_fk = 4,
                            fecha = new DateTime(2023, 10, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 2,
                            vendido = 0
                        },
                        new
                        {
                            id = 3,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 180,
                            costo = 24000.0,
                            destino_fk = 5,
                            fecha = new DateTime(2023, 10, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 3,
                            vendido = 0
                        },
                        new
                        {
                            id = 4,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 160,
                            costo = 22500.0,
                            destino_fk = 1,
                            fecha = new DateTime(2023, 10, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 4,
                            vendido = 0
                        },
                        new
                        {
                            id = 5,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 747",
                            capacidad = 130,
                            costo = 23000.0,
                            destino_fk = 2,
                            fecha = new DateTime(2023, 10, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 5,
                            vendido = 0
                        },
                        new
                        {
                            id = 6,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 170,
                            costo = 23500.0,
                            destino_fk = 3,
                            fecha = new DateTime(2023, 10, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 1,
                            vendido = 0
                        },
                        new
                        {
                            id = 7,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 140,
                            costo = 22800.0,
                            destino_fk = 4,
                            fecha = new DateTime(2023, 10, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 2,
                            vendido = 0
                        },
                        new
                        {
                            id = 8,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 747",
                            capacidad = 110,
                            costo = 21500.0,
                            destino_fk = 5,
                            fecha = new DateTime(2023, 10, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 3,
                            vendido = 0
                        },
                        new
                        {
                            id = 9,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 190,
                            costo = 24500.0,
                            destino_fk = 1,
                            fecha = new DateTime(2023, 10, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 4,
                            vendido = 0
                        },
                        new
                        {
                            id = 10,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 155,
                            costo = 22700.0,
                            destino_fk = 2,
                            fecha = new DateTime(2023, 10, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 5,
                            vendido = 0
                        },
                        new
                        {
                            id = 11,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 747",
                            capacidad = 170,
                            costo = 23500.0,
                            destino_fk = 3,
                            fecha = new DateTime(2023, 10, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 1,
                            vendido = 0
                        },
                        new
                        {
                            id = 12,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 120,
                            costo = 21000.0,
                            destino_fk = 4,
                            fecha = new DateTime(2023, 10, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 2,
                            vendido = 0
                        },
                        new
                        {
                            id = 13,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 140,
                            costo = 22800.0,
                            destino_fk = 5,
                            fecha = new DateTime(2023, 10, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 3,
                            vendido = 0
                        },
                        new
                        {
                            id = 14,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 747",
                            capacidad = 180,
                            costo = 24000.0,
                            destino_fk = 1,
                            fecha = new DateTime(2023, 10, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 4,
                            vendido = 0
                        },
                        new
                        {
                            id = 15,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 130,
                            costo = 23000.0,
                            destino_fk = 2,
                            fecha = new DateTime(2023, 10, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 5,
                            vendido = 0
                        },
                        new
                        {
                            id = 16,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 150,
                            costo = 22000.0,
                            destino_fk = 3,
                            fecha = new DateTime(2023, 10, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 1,
                            vendido = 0
                        },
                        new
                        {
                            id = 17,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 747",
                            capacidad = 160,
                            costo = 22500.0,
                            destino_fk = 4,
                            fecha = new DateTime(2023, 10, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 2,
                            vendido = 0
                        },
                        new
                        {
                            id = 18,
                            aerolinea = "Aerolínea Córdoba",
                            avion = "Boeing 787 Dreamliner",
                            capacidad = 190,
                            costo = 24500.0,
                            destino_fk = 5,
                            fecha = new DateTime(2023, 10, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 3,
                            vendido = 0
                        },
                        new
                        {
                            id = 19,
                            aerolinea = "Aerolínea Buenos Aires",
                            avion = "Airbus A320",
                            capacidad = 155,
                            costo = 22700.0,
                            destino_fk = 1,
                            fecha = new DateTime(2023, 10, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 4,
                            vendido = 0
                        },
                        new
                        {
                            id = 20,
                            aerolinea = "Aerolínea Mendoza",
                            avion = "Boeing 747",
                            capacidad = 110,
                            costo = 21500.0,
                            destino_fk = 2,
                            fecha = new DateTime(2023, 10, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 5,
                            vendido = 0
                        },
                        new
                        {
                            id = 22,
                            aerolinea = "PRUEBA",
                            avion = "PRUEBA",
                            capacidad = 110,
                            costo = 21000.0,
                            destino_fk = 19,
                            fecha = new DateTime(2023, 10, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            origen_fk = 1,
                            vendido = 0
                        });
                });

            modelBuilder.Entity("Proyecto.Hotel", b =>
                {
                    b.HasOne("Proyecto.Ciudad", "ubicacion")
                        .WithMany("hoteles")
                        .HasForeignKey("ciudad_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ciudad_fk");

                    b.Navigation("ubicacion");
                });

            modelBuilder.Entity("Proyecto.ReservaHotel", b =>
                {
                    b.HasOne("Proyecto.Hotel", "miHotel")
                        .WithMany("misReservas")
                        .HasForeignKey("hotel_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_fk");

                    b.HasOne("Proyecto.Usuario", "miUsuario")
                        .WithMany("misReservasHoteles")
                        .HasForeignKey("usuarioRH_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuarioRH_fk");

                    b.Navigation("miHotel");

                    b.Navigation("miUsuario");
                });

            modelBuilder.Entity("Proyecto.ReservaVuelo", b =>
                {
                    b.HasOne("Proyecto.Usuario", "miUsuario")
                        .WithMany("misReservasVuelos")
                        .HasForeignKey("usuarioRV_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuarioRV_fk");

                    b.HasOne("Proyecto.Vuelo", "miVuelo")
                        .WithMany("misReservas")
                        .HasForeignKey("vuelo_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vuelo_fk");

                    b.Navigation("miUsuario");

                    b.Navigation("miVuelo");
                });

            modelBuilder.Entity("Proyecto.UsuarioHotel", b =>
                {
                    b.HasOne("Proyecto.Hotel", "hotel")
                        .WithMany("hotel_usuario")
                        .HasForeignKey("hotel_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Usuario", "usuario")
                        .WithMany("usuario_hotel")
                        .HasForeignKey("usuario_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hotel");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Proyecto.UsuarioVuelo", b =>
                {
                    b.HasOne("Proyecto.Usuario", "usuario")
                        .WithMany("usuario_vuelo")
                        .HasForeignKey("usuario_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Vuelo", "vuelo")
                        .WithMany("vuelo_usuario")
                        .HasForeignKey("vuelo_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");

                    b.Navigation("vuelo");
                });

            modelBuilder.Entity("Proyecto.Vuelo", b =>
                {
                    b.HasOne("Proyecto.Ciudad", "destino")
                        .WithMany()
                        .HasForeignKey("destino_fk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("destino_fk");

                    b.HasOne("Proyecto.Ciudad", "origen")
                        .WithMany("vuelos")
                        .HasForeignKey("origen_fk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("origen_fk");

                    b.Navigation("destino");

                    b.Navigation("origen");
                });

            modelBuilder.Entity("Proyecto.Ciudad", b =>
                {
                    b.Navigation("hoteles");

                    b.Navigation("vuelos");
                });

            modelBuilder.Entity("Proyecto.Hotel", b =>
                {
                    b.Navigation("hotel_usuario");

                    b.Navigation("misReservas");
                });

            modelBuilder.Entity("Proyecto.Usuario", b =>
                {
                    b.Navigation("misReservasHoteles");

                    b.Navigation("misReservasVuelos");

                    b.Navigation("usuario_hotel");

                    b.Navigation("usuario_vuelo");
                });

            modelBuilder.Entity("Proyecto.Vuelo", b =>
                {
                    b.Navigation("misReservas");

                    b.Navigation("vuelo_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
